name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phpunit

    steps:
    - uses: actions/checkout@v2

    - name: Versions
      run: |
        php --version
        composer --version
        phpunit --version

#     - name: Validate composer.json and composer.lock
#       run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer test
