name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: phpunit

    steps:
    - uses: actions/checkout@v3

    - name: Versions
      run: |
        php --version
        composer --version
        phpunit --version

#     - name: Validate composer.json and composer.lock
#       run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Dump autoload
      run: composer dump-autoload

    - name: Run test suite
      run: composer test tests/
